version: "1.0"
info:
  model: int-scaffold
packages:
- name: Demo4UseCaseModernisationProject
  gitServerName: mhbgit
  gitUrl: https://github.com/mhbabchia-eviden
  gitUsername: mhbabchia-eviden
  gitBranch: main
- name: mhbDescApiPackage
  version: "1.0"
  gitServerName: mhbgit
  gitUrl: https://github.com/mhbabchia-eviden
  gitUsername: mhbabchia-eviden
  gitBranch: develop
- name: mhbApi
  version: "1.0"
  gitServerName: mhbgit
  gitUrl: https://github.com/mhbabchia-eviden
  gitUsername: mhbabchia-eviden
  gitBranch: develop
services:
- serviceName: project.demo4usecasemodernisation.integrations:UserService
  packages:
  - name: Demo4UseCaseModernisationProject
    version: "1.0"
  - name: mhbApi
    version: "1.0"
  - name: mhbDescApiPackage
    version: "1.0"
- serviceName: mhbApi.userResource_.services:getUserByIdService
  packages:
  - name: mhbApi
    version: "1.0"
- serviceName: project.demo4usecasemodernisation.integrations:orderServiceDemo
  packages:
  - name: Demo4UseCaseModernisationProject
    version: "1.0"
  - name: mhbApi
    version: "1.0"
  - name: mhbDescApiPackage
    version: "1.0"
- serviceName: org.atos.api.StockApi_.services:GET_stock_svc1
  packages:
  - name: mhbDescApiPackage
    version: "1.0"
