version: "1.0"
info:
  model: int-scaffold
packages:
- name: Demo4UseCaseModernisationProject
  gitServerName: mhbgit
  gitUrl: https://github.com/mhbabchia-eviden
  gitUsername: mhbabchia-eviden
  gitBranch: main
- name: mhbDescApiPackage
  gitServerName: mhbgit
  gitUrl: https://github.com/mhbabchia-eviden
  gitUsername: mhbabchia-eviden
  gitBranch: develop
services:
- serviceName: project.demo4usecasemodernisation.integrations:orderServiceDemo
  packages:
  - name: Demo4UseCaseModernisationProject
    version: "1.0"
